function opts_out = get_dynia_options(opts_in)

defaultopt = struct('repeats', 2e5, ...
                    'of_name', 'of_KGE', ...
                    'window_size', 31, ...
                    'window_step', 1,...
                    'file_prefix', 'DYNIA', ...
                    'chunk_size', 1000,...
                    'precision_Q', 4, ...
                    'precision_OF', 4,...
                    'perf_thr', 0,...
                    'display', 1,...
                    'overwrite', 0);
defaultopt.of_args = cell(0);

% get options
opts_out.n = optimget(opts_in, 'repeats', defaultopt, 'fast');
opts_out.of_name = optimget(opts_in, 'of_name', defaultopt, 'fast');
opts_out.window = optimget(opts_in, 'window_size', defaultopt, 'fast');
opts_out.step = optimget(opts_in, 'window_step', defaultopt, 'fast');
opts_out.file_prefix = optimget(opts_in, 'file_prefix', defaultopt, 'fast');
%opts_out.c_size = optimget(options, 'chunk_size', defaultopt, 'fast');
opts_out.precision_Q = optimget(opts_in, 'precision_Q', defaultopt, 'fast');
opts_out.precision_OF = optimget(opts_in, 'precision_OF', defaultopt, 'fast');
opts_out.of_args = optimget(opts_in, 'of_args', defaultopt, 'fast');
opts_out.perf_thr = optimget(opts_in, 'perf_thr', defaultopt, 'fast');
opts_out.display = optimget(opts_in, 'display', defaultopt, 'fast');
opts_out.overwrite = optimget(opts_in, 'overwrite', defaultopt, 'fast');